services:
  postgres:
    image: postgres:18.3
    container_name: postgres2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"